-- MySQL Script generated by MySQL Workbench
-- Fri Oct  9 20:46:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema documentos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema documentos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `documentos` DEFAULT CHARACTER SET utf8 ;
USE `documentos` ;

-- -----------------------------------------------------
-- Table `documentos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `documentos`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido` VARCHAR(50) NOT NULL,
  `Clave` VARCHAR(10) NOT NULL,
  `Usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `documentos`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `documentos`.`Estado` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `documentos`.`Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `documentos`.`Documento` (
  `id_docu` INT NOT NULL AUTO_INCREMENT,
  `nombre_docume` VARCHAR(45) NOT NULL,
  `contenido` VARCHAR(5000) NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  `fk_id_estado` INT NOT NULL,
  PRIMARY KEY (`id_docu`, `fk_id_usuario`, `fk_id_estado`),
  INDEX `fk_Documento_Usuario_idx` (`fk_id_usuario` ASC) VISIBLE,
  INDEX `fk_Documento_Estado1_idx` (`fk_id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_Documento_Usuario`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `documentos`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documento_Estado1`
    FOREIGN KEY (`fk_id_estado`)
    REFERENCES `documentos`.`Estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
